name: generate new data

on:
  schedule:
    - cron: '0 7 * * *'

  push:
    branches: 'main'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: pip install requests

      - name: Run main script
        env:
          SOME_SECRET: ${{ secrets.TOKEN }}
        run: python dump.py

      - name: Commit and Push XML files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Actions"
          git add "data/*.xml"
          git commit -m "Update daily xml"
          git push
          
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: main
